# cd.yml
name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Frontend
        uses: appleboy/rsync-action@v0.1.3
        with:
          local_path: frontend/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: /var/www/html/frontend

      - name: Sync Backend
        uses: appleboy/rsync-action@v0.1.3
        with:
          local_path: ./
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: /var/www/html/backend
          exclude: |
            frontend/
            node_modules/
            vendor/

      - name: Install Backend Dependencies & Migrate
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/backend
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan db:seed --force
            php artisan config:cache
            php artisan route:cache
