name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [ test-frontend, test-backend ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Sync Frontend via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            frontend/.next/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/frontend
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            frontend/public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/frontend/public

      - name: Sync Backend via rsync
        run: |
          rsync -avz --delete \
            --exclude 'node_modules/' \
            --exclude 'vendor/' \
            --exclude 'frontend/' \
            -e "ssh -o StrictHostKeyChecking=no" \
            backend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/backend

      - name: Finalize Backend Setup
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/backend
            # install optimized dependencies
            composer install --no-dev --optimize-autoloader
            # run migrations & seeds
            php artisan migrate --force
            php artisan db:seed --class=ProductionSeeder
            # cache config & routes
            php artisan config:cache
            php artisan route:cache
            # fix permissions
            chmod -R ug+rwx storage bootstrap/cache
