name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    name: Test Next.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Run lint
        run: |
          cd frontend
          npm run lint
      - name: Run tests
        run: |
          cd frontend
          npm test

  test-backend:
    name: Test Laravel
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, xml, curl
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Copy .env
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Prepare Database
        run: php artisan migrate --force
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-text
        